on: push
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Deploy Angular to GitHub Pages
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
